classes:
  Necromancer:
    abilities:
      - LifeDrain
      - PlagueCloud
      - MistDash
      - Tentacles
      - BoneChoir
      - UndyingRage
  Archdruid:
    abilities:
      - NatureStep
      - AmbushSlash
      - SporeBlossom
      - CanopyCrash
      - QuillflareSurge
      - IronwoodShell
  Lightbringer:
    abilities:
      - LightCage
      - Consecration
      - PurifyingPrism
      - RadiantPhase
      - RadiantDash
      - BeaconOfClarity
  Mindshaper:
    abilities:
      - EchoPulse
      - PhantomEcho
      - NeuralTrap
      - Dreamwalker
      - ShadowCreatures
      - CloneSwarm
  Elementalist:
    abilities:
      - Tidepool
      - Emberstorm
      - GaleVortex
      - EarthShards
      - Avalanche
      - ThunderSlam
  Runesmith:
    abilities:
      - WardingSigil
      - Runecarver
      - RunicJumpPad
      - RunicCannon
      - BladeSpin
      - SwarmSigil


# Global ability settings or specific ability settings
abilities:
  ambushslash:
    mana-cost: 50
    required-class: "archdruid"
    cooldown: 12
    stage1-damage: 3.5
    stage2-damage: 6.0
    mark-duration-ticks: 40
    nature-burn:
      duration-ticks: 60
      amplifier: 1
      spread-radius: 2.0
    teleport-offset: 1.2
    blast-range: 5.0
    blast-check-radius: 1.0
    projectile-speed: 1.5
    spiral-radius: 0.4
    spiral-speed: 0.7853981633974483

  avalanche:
    cooldown: 10
    mana-cost: 40
    base-radius: 2.0
    max-radius: 6.0
    initial-speed: 0.3
    speed-gain: 0.05
    max-speed: 1.2
    damage: 5.0
    knockback-strength: 1.5
    max-duration: 100
    growth-rate: 0.15
    hit-cooldown-ticks: 20
    required-class: "elementalist"

  beaconofclarity:
    cooldown: 20
    mana-cost: 60
    required-class: "lightbringer"
    beacon-radius: 5.0
    duration-ticks: 200
    heal-amount: 2.0
    max-total-heal-per-ally: 4.0
    heal-interval-ticks: 20

  bladespin:
    cooldown: 20
    mana-cost: 50
    required-class: "runesmith"
    duration: 5.0
    radius: 2.5
    damage: 1.5
    max-hits: 3
    forward-speed: 0.6
    bounce-strength: 1.5
    bounce-cooldown: 10
    hit-cooldown: 10
    dash-speed: 4
    dash-duration-ticks: 4

  bonechoir:
    cooldown: 45
    duration: 30
    formationRadius: 4.0
    hardTeleportThreshold: 25.0
    idealCombatDistance: 15.0
    maxEffectiveRange: 15.0
    tenorSkillCooldown: 40
    baritoneSkillCooldown: 160
    bassSkillCooldown: 120

  canopycrash:
    cooldown: 15
    mana-cost: 25
    required-class: "archdruid"
    damage: 3.0
    radius: 5.5
    vertical-knockback: 0.8
    horizontal-knockback: 1.2
    particle-count: 30
    min-height: 4.0

  naturestep:
    cooldown: 8
    mana-cost: 20
    required-class: "archdruid"
    dash-distance: 7.0
    dash-speed: 1.2

  sporeblossom:
    cooldown: 18
    mana-cost: 35
    required-class: "archdruid"
    radius: 4.0
    duration-ticks: 100
    damage-per-tick: 1.0
    tick-interval: 20

  quillflaresurge:
    cooldown: 22
    mana-cost: 40
    required-class: "archdruid"
    projectile-count: 8
    projectile-speed: 1.5
    damage: 2.5
    spread-angle: 30

  ironwoodshell:
    cooldown: 30
    mana-cost: 45
    required-class: "archdruid"
    duration-ticks: 120
    damage-reduction: 0.4

  lifedrain:
    cooldown: 10
    mana-cost: 30
    required-class: "necromancer"
    drain-amount: 2.0
    duration-ticks: 60
    tick-interval: 10

  plaguecloud:
    cooldown: 20
    mana-cost: 35
    required-class: "necromancer"
    radius: 5.0
    duration-ticks: 120
    damage-per-tick: 1.2
    tick-interval: 20

  mistdash:
    cooldown: 6
    mana-cost: 15
    required-class: "necromancer"
    dash-distance: 6.0
    dash-speed: 1.0

  tentacles:
    cooldown: 25
    mana-cost: 40
    required-class: "necromancer"
    tentacle-count: 4
    damage: 2.0
    range: 5.0

  undyingrage:
    cooldown: 60
    mana-cost: 80
    required-class: "necromancer"
    duration-ticks: 100
    heal-per-tick: 1.0
    tick-interval: 10

  lightcage:
    cooldown: 18
    mana-cost: 35
    required-class: "lightbringer"
    radius: 3.5
    duration-ticks: 80

  consecration:
    cooldown: 20
    mana-cost: 40
    required-class: "lightbringer"
    radius: 4.0
    duration-ticks: 100
    damage-per-tick: 1.5
    tick-interval: 20

  purifyingprism:
    cooldown: 25
    mana-cost: 50
    required-class: "lightbringer"
    radius: 5.0
    heal-amount: 3.0

  radiantphase:
    cooldown: 12
    mana-cost: 25
    required-class: "lightbringer"
    phase-distance: 8.0
    phase-speed: 1.3

  radiantdash:
    cooldown: 8
    mana-cost: 20
    required-class: "lightbringer"
    dash-distance: 7.0
    dash-speed: 1.2

  echopulse:
    cooldown: 10
    mana-cost: 30
    required-class: "mindshaper"
    damage: 2.0
    range: 10.0

  phantomecho:
    cooldown: 16
    mana-cost: 35
    required-class: "mindshaper"
    clone-count: 2
    duration-ticks: 60

  neuraltrap:
    cooldown: 20
    mana-cost: 40
    required-class: "mindshaper"
    trap-radius: 3.0
    duration-ticks: 80
    damage: 2.5

  dreamwalker:
    cooldown: 30
    mana-cost: 60
    required-class: "mindshaper"
    duration-ticks: 120
    invisibility: true

  shadowcreatures:
    cooldown: 25
    mana-cost: 50
    required-class: "mindshaper"
    creature-count: 3
    duration-ticks: 100

  cloneswarm:
    cooldown: 40
    mana-cost: 70
    required-class: "mindshaper"
    clone-count: 5
    duration-ticks: 80

  tidepool:
    cooldown: 12
    mana-cost: 30
    required-class: "elementalist"
    radius: 3.0
    duration-ticks: 60
    slow-amount: 0.5

  emberstorm:
    cooldown: 18
    mana-cost: 40
    required-class: "elementalist"
    radius: 4.0
    duration-ticks: 80
    damage-per-tick: 1.8
    tick-interval: 20

  galevortex:
    cooldown: 20
    mana-cost: 45
    required-class: "elementalist"
    radius: 5.0
    duration-ticks: 100
    pull-strength: 1.2

  earthshards:
    cooldown: 15
    mana-cost: 35
    required-class: "elementalist"
    shard-count: 4
    damage: 2.2

  thunderslam:
    cooldown: 22
    mana-cost: 50
    required-class: "elementalist"
    radius: 4.5
    damage: 4.0

  wardingsigil:
    cooldown: 10
    mana-cost: 20
    required-class: "runesmith"
    duration-ticks: 60
    shield-amount: 3.0

  runecarver:
    cooldown: 18
    mana-cost: 35
    required-class: "runesmith"
    rune-count: 3
    duration-ticks: 80

  runicjumppad:
    cooldown: 12
    mana-cost: 25
    required-class: "runesmith"
    jump-force: 2.0
    duration-ticks: 40

  runiccannon:
    cooldown: 20
    mana-cost: 45
    required-class: "runesmith"
    damage: 3.5
    range: 12.0

  swarmsigil:
    cooldown: 25
    mana-cost: 55
    required-class: "runesmith"
    swarm-count: 4
    duration-ticks: 100